src/lang/pt-PT.json

Added Missing translations for:
"MENU_CHECK_FOR_UPDATES": "Check For Updates...",
"// 15": "Dialogs ------------------------------------------------------",
"DIALOG_DOWNLOAD": "Download",
"DIALOG_SKIP_VERSION": "Skip This Version",
"DIALOG_REMIND_LATER": "Remind Me Later",
"DIALOG_OK": "OK",
"DIALOG_CANCEL": "Cancel",
"DIALOG_UPDATE_AVAILABLE": "Update available",
"DIALOG_UPDATE_DESCRIPTION": "GB Studio {version} available. Would you like to update?",
"DIALOG_UPDATE_DONT_ASK_AGAIN": "Dont ask me again",
"DIALOG_UP_TO_DATE": "You’re up-to-date!",
"DIALOG_NEWEST_VERSION_AVAILABLE": "GB Studio {version} is currently the newest version available.",
"DIALOG_UNABLE_TO_CHECK_LATEST_VERSION": "Unable to check latest version at the moment",

Updated pt-PT.json with the new terms added on the en.json

---

appData/src/gb/src/gbt_player_bank1.s
src/lib/vendor/scriptracker/mod_module.js

Music Test proj is nearly done.
Doc has been updated, pan is a supported effect on ch4 again.
https://github.com/chrismaltby/gb-studio-site/pull/8/
* **What kind of change does this PR introduce?** Bug fix
GBTplayer had hex values wrong for Ch4 pan, causing it to break.
Mod JS tracker now has higher range matching the gameboy,
disabled some effects in the js tracker that are not supported by gbt.
Playing pan fx on ch4 would mute ch4
High notes clamped to a pitch lower than in game.
Playing pan fx on ch4 pans the channel left or right
High notes play the same pitch as in game.
* **Does this PR …

Fix gbt ch4 pan fx, Minor Improvements to js mod player

---

src/components/script/ScriptEventBlock.js

This is a bug fix for the dialogue textarea.
The cursor was jumping when editing a section of the textarea. You can reproduce by adding text to the textarea, moving the cursor to an earlier point, and typing more text. This is because the textarea contents are rewritten in the dialogue box.
The textarea saves and restores the correct cursor position when editing.

Restore cursor position after textarea has been edited.

---

appData/src/gb/src/Scene_b.c

Bug fix #237 add check to general actors update so a moving static is not forced to animate.
A multi frame actor set to static would still animate when moving via script.
A multi frame actor set to static will not animate when moving via script, unless set directly.
* **Does this PR introduce a breaking change?** 
If the user intended this effect, they could switch to face interaction? 
Made sure that a cycling static actor will still animate when moving.

Stop Static multiframe actors animating when moving

---

appData/src/gb/include/Scene.h
appData/src/gb/src/Scene_b.c
appData/src/gb/src/ScriptRunner_b.c
src/lib/compiler/scriptBuilder.js

* **What kind of change does this PR introduce?** (Bug fix, feature.)
Changes an oversight where the **fastest camera** move to speed was **every second frame**.
Also fixes **Camera : lock to player** only supporting **instant**, or **every frame**.
* **What is the current behavior?** 
Code is calculated in **ScriptBuilder.js,**
**6**th bit set for transitioning, 
low **4** bits are masked, then bitwise **&** against time binary, if=0, moves cam 1px.
Speed **0** (instant), value 0 (instant)`binary 0000-0000`
Speed **1** (Faster), 32+1 (every **2**)   `binary 1000-0100`
Speed **2**, 32+ 3    ( move every **4** )   `binary 1100-0100`
Speed **3**, 32+ 7   (every **8** frames)  `binary 1110-0100`
Speed **4**, 32+15 (every **16** frame) …

Increase CameraMoveTo speed and fix lock to player speed

---

src/actions/index.js
src/lib/helpers/fs/writeFileAndFlush.js
src/lib/helpers/fs/writeFileWithBackup.js
src/lib/project/saveProjectData.js
test/helpers/fs/writeFileAndFlush.test.js
test/helpers/fs/writeFileWithBackup.test.js

Bug fix for issue saving project data
In very rare instances in the Windows version it's possible for the project file to be written to an in memory cache but not written to the file system causing complete loss of the project data file. To my knowledge this has happened twice so far. Similar issues have been seen in VSCode, Notepad++ and Aseprite as referenced in the reported issue #262 
A replacement to fs.writeFile has been written (based partially on a fix submitted for the same issue in VSCode …

fix for issues/262 flushing data after write and add backup of previous data

---

appData/src/gb/src/Scene_b.c

Bug fix
Actors placed on Y=31 are not collidable. This is because in engine the actor positions are stored in pixel values and converted to tile values when needed by dividing by 8, Y=31 in editor is Y=256 ingame and since the position is stored as an 8-bit int it is actually Y=0 causing checks for actors at this tile position to not be found.
Updated NPC at tile checks to account for this behaviour
No
Fixes #255

Fix collision bug at bottom edge of screen

---

appData/src/gb/src/UI.c
test/projects/Test_TextWithAvatar/Test_TextWithAvatar.gbsproj

#284 introduced a bug in any dialogue (with or without avatar) that counted the line break characters as a new tile, effectively reducing the max numbers of characters by 2 and allowing the overflow reported in issue #291. 
This fix reverts to the same behavior as before #284 but using a slightly different code.
The image shows how the following text is stored in the tile data for each of those versions:
```
123456789123456789
123456789123456789
1234567891234567
```
No functional change but fixes issue https://github.com/chrismaltby/gb-studio/issues/291
The dialogue …

Skip new line character when adding to dialogue

---

package.json
src/components/script/AddCommandButton.js
yarn.lock

Fixes #246.
Bug fix
Using the keyboard to navigate through the event list doesn't scroll along with the selected item, causing the selected list item to be out of view. #246 
The list scrolls to the selected item when necessary.
It shouldn't!
I introduced a small dependency, `react-scroll-into-view-if-needed`. This is my first PR in this project and I'm unsure if …

Scroll 'Add Event' list items into view when necessary

---

appData/js-emulator/js/other/controls.js

Feature
Absence of gamepad support.
Adds gamepad support, activates if gamepad button is pressed with js Game Boy emulator has focus.
No changes should be required.
When w3c "standard" mapping is available for the gamepad, buttons will map to the expected locations Otherwise the first 4 buttons map to A/B/Select/Start.
Gamepad support co-exists and does not …

JS Game Boy Emulator: Add gamepad support

---

appData/js-emulator/js/GameBoyCore.js
appData/js-emulator/js/GameBoyIO.js
appData/js-emulator/js/other/XAudioServer.js

Bug fix
* **What is the current behavior?** 
Audio was mono, had major crackle on chrome android, could cause clicking if in the background on some devices.
Did not play until a button was pressed. #177
Audio is stereo again, and play's better on all devices (optimized, and buffer increased to 4096). 
Sound starts as soon as emulation begins now. 
Overall sound volume is the same as 1.1 (Half volume).
* **Does this PR introduce a breaking change?** 
Not likely!
Pop fix being done in the gameboy core let me remove the code blob from last dc offset pop fix, which …

Fix JS GameBoy emulator audio

---

appData/src/gb/include/Macros.h
appData/src/gb/include/Scene.h
appData/src/gb/src/Scene_b.c
appData/src/gb/src/ScriptRunner_b.c
src/lib/events/eventActorMoveTo.js
src/lib/events/eventActorSetPosition.js
src/lib/events/eventIfActorAtPosition.js
src/lib/events/eventSceneSwitch.js

Prevents actors from walking off scene edges fixing the issues seen in #315
Walking off scene edges has inconsistent collision handling requiring a strip of collisions to be placed around all four edges of a scene to be certain that the player can't walk through edges.
Actors now stop walking at scene edges allowing a larger area of the map to be used for the walking area with no manual collision setup required.
If anyone was depending on …

Prevent actors from exiting scene edges

---

appData/src/gb/include/BankManager.h
appData/src/gb/include/game.h
appData/src/gb/src/BankManager.c
appData/src/gb/src/ScriptRunner_b.c
src/lib/compiler/bankedData.js
src/lib/compiler/compileData.js
src/lib/compiler/helpers.js
src/lib/compiler/makeBuild.js
test/data/compiler/bankedData.test.js

Fix MBC1 support, using correct GBDK banking functions when enabled and avoiding banks 0x20, 0x40 and 0x60 for data and music based on issue noted in #317 
When MBC1 is enabled as the memory bank controller in project settings the game engine was still using the GBDK functions for MBC5 which would likely not work on real cartridges. Also when MBC1 is enabled banks 0x20, 0x40, and 0x60 cannot be used and should be avoided.
When MBC1 is selected in settings the C headers are modified to use MBC1 functions instead of MBC5, also data and music will no longer be stored …

Fix MBC1 support

---

src/components/forms/SceneActorSelect.js
src/lib/compiler/scriptBuilder.js

Adds a new `Self` option to Actor Selector fields inside Actor Scripts
When copy and pasting an Actor with scripts that reference itself all the Actor select fields need to be set to the new Actor again.
When selected, "Self" always references the current actor. So when the actor is copied it'll reference the newly created Actor rather than the previous one.
No

Add "Self" to Actor select

---

src/lib/vendor/scriptracker/channel.js
src/lib/vendor/scriptracker/effects.js
src/lib/vendor/scriptracker/mod_module.js
src/lib/vendor/scriptracker/sample.js
src/lib/vendor/scriptracker/scriptracker.js

* **What kind of change does this PR introduce?**
Bug fix / feature.
Split of #294 to make merging easier.
Related to #172, #83 and partly #176
The in editor music preview is very inaccurate and will play any mod files without GameBoyTracker limits, leading to confusion and not being useful for previewing common mistakes.
Notes use last set volume instead of the default sample volume.
Channel 4 Noise is forced to note C5.
Instruments are limited to their channels, (no pulse waves on the noise track.)
Forced pan to hard left, both, or hard right.
Tick speed changes the tempo to match in game …

Improve in editor music scriptracker.js to act like GBT

---

src/reducers/entitiesReducer.js

Only keeps if it's the same width, and if there's no other collision currently for that background.
Feature / bug fix
When you change the background of a scene containing collision, it destroys the current collision and either copies collision if a scene with that background has some, or clears it.
If you change the background of a scene to one that has not been used yet, and is the same width, it will keep your current collision.
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to …

Editor keep scene collision when switching to bg without collision

---

appData/src/gb/src/UI.c

Bug fix
Menu and Choice Option Events override the user defined text draw speed in order to render immediately. That speed isn't restored after the menu was closed so following text dialogues were rendering at fast speed.
Last used draw speed is stored in a temporary variable before being override when showing a menu and then it's restored once the menu text is rendered.
None

Restore last draw speed after drawing a menu

---

src/components/forms/GlobalVariableSelect.js
src/reducers/editorReducer.js
src/reducers/initialState.js

Bug fix
When a variable selector is opened the list of variable names is cached so that if you open one selector, rename a variable in a second selector, and open the first one again the rename will not be displayed. First reported in #352 
When any variables are renamed all variable selectors currently on screen will now rerender causing their internal cache to clear.
No

Variable list update on rename

---

CHANGELOG.md
src/components/world/SceneCursor.js

Bug fix
When the global setting "Show Collisions" is turned off, collisions are still visible when using the Collisions tool but trying to place/remove collisions does not work.
The collisions tool works as expected regardless of the "Show Collisions" setting. When "Show Collisions" is off and any other tool is selected the collisions will be hidden but if the collisions tool is selected the collisions will be visible and can be edited.
No

Fix for #351 where collisions couldn't be edited

---

src/components/script/AddCommandButton.js

Bug fix
Holding the Alt key while switching to another application away from GB Studio then releasing the Alt key before returning (as may happen when using Alt+Tab on Windows but issue is on all platforms) will cause "Add Event" buttons to become stuck as "Paste Event" buttons until Alt is pressed and released again or the selected entity is changed.
When the GB Studio window becomes blurred the "Paste Event" buttons become "Add Event" buttons again.
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to …

Fix #343 where paste event button getting stuck when switching window while holding Alt key

---

package.json
src/components/forms/CustomPalettePicker.js
yarn.lock

Bug fix
In the colour palette picker, entering a hex code and clicking "Convert Hex" will result in a slightly different colour being used in game than the hex code represents. This is because the in game emulator uses a function to tint the colours to match the GBC display.
The "Convert Hex" now calls an inverse of the tint function to find the closest matching hex that will display in game as the intended colour. An equation solver was added to determine the closest value and as the tint function is lossy it's not 100% guaranteed that passing a value through the …

Fix convert hex to take into account color palette transform occurring in GBC emulator

---

appData/src/gb/src/Scene_b.c
src/lib/events/eventTimerScriptSet.js

Bug fix & feature
#353 Show overlay halts timerscript
https://discordapp.com/channels/554713715442712616/585023243732123676/652881193359900695
Timer script faster please? https://discordapp.com/channels/554713715442712616/570925583421276160/654859741788504106
1. Allows show overlay at the end of a script, timer script still pauses for dialogue or anything during script.
2. Change the minimum timer script speed to 0.25 seconds and step in 0.25 increments instead of 0.05. 
Timer script ticks every 16 frames, about 0.26 seconds, so this is the …

Fix timer script with show overlay, faster min speed, and performance improvement.

---

appData/src/gb/include/Scene.h
appData/src/gb/src/Scene.c
appData/src/gb/src/Scene_b.c
appData/src/gb/src/game.c

Bug fix. 
On scene, sprite position sometimes gets out of sync with background.
(It might be hard to appreciate in the GIF, but the rock sprite moves one pixel up and down as the player walks and the scene scrolls)
`SCX_REG` and `SCY_REG` are now updated on a VBL interrupt. Keeping backgrounds and sprites in sync.
(the rock sprite stays in the same position with the scene scroll)
After some quick tests, doesn't seem to break anything. However …

Update scroll registers on VBL interrupt

---

appData/src/gb/include/ScriptRunner.h
appData/src/gb/src/ScriptRunner.c
appData/src/gb/src/ScriptRunner_b.c
src/lib/compiler/compileEntityEvents.js

Bug fix for invoke actor, similar to the last invoke actor fix.
#369  Invoke actor will cause a crash on return if the actor scripts are in different script banks.
Rare bug, only dealing with large scripts that happen to be in different banks.
May be slightly slower for invoke actor events, but will fix a game crash that is not easy to work around. the demo in #369 will work now.
* **Does this PR introduce a breaking change?**
Scripts that call actor invoke frequently in a loop may notice more lag, but it's already pretty slow, label define and …

Fix Invoke actor for scripts in other banks

---

src/lib/helpers/stripInvalidFilenameCharacters.js
test/helpers/stripInvalidFilenameCharacters.test.js

Bug fix adding additional checks in `stripInvalidFilenameCharacters` helper preventing broken profile filenames being created on Windows (seen in #368)
The characters `[` and `]` as well as a few others that are invalid are allowed in project file names causing GB Studio to try to create a project with an invalid filename on Windows
Additional characters have been added to the `stripInvalidFilenameCharacters` function preventing them from being used when creating the project.
* **Does this PR introduce a breaking change?** (What changes might users need to make in …

Fix for #368. Strip invalid filename characters when creating project

---

appData/src/gb/src/UI.c

Fixes a bug reported [on discord](https://discordapp.com/channels/554713715442712616/570925559346102273/669025434494828548) where the text speed is only respected on the first text event but to normal speed after. This bug was introduced with the fix for #361. 
To reproduce the bug run talk with the actor in this project using 1.2.1 [text_speed.zip](https://github.com/chrismaltby/gb-studio/files/4092084/text_speed.zip).
Simplifies the code that makes Menu and Choice Events to render text immediately. 
Previously the text speed was hardcoded to zero for menus, the …

Draw text buffer immediatly on menu dialogue

---

appData/src/gb/include/UI.h
appData/src/gb/src/ScriptRunner.c
appData/src/gb/src/ScriptRunner_b.c
appData/src/gb/src/UI.c
src/lib/compiler/bankedData.js
src/lib/compiler/compileData.js
src/lib/compiler/compileEntityEvents.js
src/lib/compiler/scriptBuilder.js
test/data/compiler/compileEntityEvents.test.js
test/data/compiler/scriptBuilder.test.js

Bug fix for #404 where a project contained enough text to stop the `string_bank_ptrs` array from fitting within bank 5 causing an overflow.
Bank 5 contains an array of pointers to each string in memory. When displaying a string such is in a Display Dialogue event it is looked up by index in the array (16bit value) to find the bank it's stored in (8bit value) and it's offset in the bank (16bit value)
The `string_bank_ptrs` array has been removed entirely and instead every time a string is needed the bank and offset is stored directly within the event.
So where …

Remove string_bank_ptrs array, instead inject string_ptrs directly into script arguments

---

src/lib/compiler/buildProject.js
src/lib/compiler/compileData.js
src/lib/compiler/compileMusic.js

Feature and bugfix!
Too much music causes bad bank allocation, current system just loops over 8 banks without care.
#388 wrote twice at addr, similar to #404 too.
Estimates music size after compile and modify bank_ptrs.c to fit more tracks in.
Helps tremendously with lots of smaller tracks and a few big tracks.
Music size is currently an approximate based on output file length, will overestimate for safty
Auto expands properly, log in place to hook in to #410 for auto cart size.
* **Does this PR introduce a breaking change?** (What changes might …

Music Bank Dynamic Allocation Feature/Bugfix

---

appData/src/gb/src/UI_b.c

Bug fix
* **What is the current behavior?**
If the cursor is dynamically allocated a bank before or after ui border, we would read garbage.
This has been a rare issue before this, where the cursor would be in the next bank over, but has been more apparent with dynamic filling as the tile is small.
#410
Read the cursor bank, have the correct cursor, easy to do, hard to find.
* **Does this PR introduce a breaking change?** 
None!

Fix bad cursor when frame and cursor bank differ

---

appData/js-emulator/css/style.css
appData/js-emulator/js/other/XAudioServer.js
appData/js-emulator/js/other/controls.js

Bug fix, feature
Audio latency is high on all devices to specifically fix chrome on android,
If you try to play in landscape, you will be asked to rotate your screen on mobile, in some configurations with itch this is not possible.
Audio latency is returned to 2048 as originally designed (most computers can go lower, but this is the limit for Firefox android). Exception for Chrome Android to set the buffer to 4096.
Putting the phone in landscape mode will no longer ask you to rotate, and instead uses a gba style layout, works great on ultra wide …

JavaScript emulator latency and landscape mode

---

src/lib/helpers/fsCopy.js

After debugging #398 , I found that the application was getting stuck during the recursive copying of build tools. Noticing that using a combination of fs.readFile/fs.writeFile is sub-optimal, I rewrote it to utilize streams instead - which also happened to fix the problem for me.
No. This PR should be invisible to the end-user.

Use streams instead of read/writes for copying files; may help with #398

---

src/lib/compiler/compileData.js

Add compile warning if player sprite sheet is set to `None`.
Compile fails with `TypeError: Cannot read property 'plugin' of undefined` when no sprite sheet has been selected for the Player. See #447 
A more clear `Player Sprite Sheet isn't set. Please, make sure to select a Sprite Sheet in the Project editor.` error is shown on compile.
No
This doesn't solve the …

Add compile warning if player sprite sheet isn't set

---

src/components/world/Connections.js
src/lib/helpers/eventSystem.js

Bug fix. 
Connections within scenes aren't being detected for scripts other than the main one on each entity. Connectors aren't displayed in the World editor when `Change Scene` event is used on those scripts.
Walk over all the scripts for each entity to detect `Change Scene` events.
No. Although it might make things a bit slower?

Walk all scripts for scene connection detection

---

src/reducers/entitiesReducer.js

Bug fix, colours were not cleared like collisions if a scene is resized.
Easy way out, no dynamic padding to try and keep data.
Color data is garbled after scene resize #450 
Color data is cleared after scene resize.
Nope
Migrating pull requests over to main repo.

V2 Fix, when a scene has changed size, clear colours like collisions

---

appData/src/gb/src/core/Core_Main.c

Bug fix
Unlike 1.2.1, if you load a background between 192-256 tiles, then a background with less than 192 tiles, the text box will be using garbage tiles from the last bg. #454 
Reverts to 1.2.1 where UI tiles are loaded every time before the next scene, in case they were overwritten.
Dialogue still corrupt on scenes 192-256, but fine again once you move to a sub 192 unique tile map. …

V2 Fix, Refresh UI before Scene switch (in case last bg 192+ overwrote it)

---

src/lib/compiler/compileEntityEvents.js

Labels defined outside subscripts (like timer or input script) where being passed to the compile. That made possible to use go to those labels without a compile error, leading to broken game behavior (see #484 )
Bug fix
Labels defined outside subscripts (like timer or input script) where being passed to the compile. That made possible to use go to those labels without a compile error, leading to broken game behavior (see #484  )
Subscripts (like timer or input script) receive an empty list of labels, so the …

Don't pass labels definition to when compiling subscripts

---

appData/src/gb/src/core/ScriptRunner_b.c
src/components/script/ScriptEventForm.js
src/lang/en.json
src/lib/compiler/scriptBuilder.js
src/lib/events/eventVariableMath.js
test/data/compiler/scriptBuilder.test.js
test/events/eventVariableMath.test.js

Feature: Allow add and subtract with no 'wrap' but 'clamp' from 0-255.
If 'Clamp' option is true, the sum will be up to 255, and the difference will be down to 0.
If 'Clamp' option is false, nothing changes.
I think it's handy in some combat system or loot system.
255 + 1 = 0
0 - 1 = 255
If 'clamp' is true:
255 + 1 = 255
0 - 1 = 0
No
L10n not completely yet. The …

Add 'Clamp' option in Add/Subtract.

---

src/components/forms/CustomEventPropertySelect.js
src/lib/compiler/compileEntityEvents.js
src/lib/compiler/helpers.js
src/lib/events/eventCallCustomEvent.js
src/lib/helpers/eventSystem.js
src/reducers/entitiesReducer.js

Adds support for Property fields in unions to Custom Events.
Property fields aren't supported
When property is selected in an union field inside a Custom Event a selector appears that allow to choose between the properties of the Custom Events actors (A to J) and the Player. If an actor that isn't the player is selected it gets added to the parameter list.
No
I …

Add support for property fields in Custom Events

---

appData/src/gb/src/ScriptRunner.c
appData/src/gb/src/ScriptRunner_b.c
appData/src/gb/src/UI.c
appData/src/gb/src/game.c

Legacy bug fix/features
Sound effects could be interrupted by music easily, music lag was considerably high for most scripts
Sound effects mute the appropriate music channels to not be overwritten, 
Improvements to script runner performance brought over from 2.0, some extreme music slowdowns reduced 10-40%, but are still moderate...
Added default Hold B to fast forward text similar to 2.0
* **Does this PR introduce a breaking change?**
No way to disable Hold B to fast forward text in 1.2, as the event would …

Engine improvements for 1.2/Dragonborne, Sfx, Script Perf, B fast forward dialogue

---

appData/src/gb/src/states/TopDown.c

Add passive collisions to top down as mentioned in #451 
In TopDown mode actors don't collide with the player when it's not moving. Other scene types like Platformer or Adventure support passive collisions.
If an actor collides with a player, even if the player isn't moving `On Player Hit` and the Actor `On Hit > Player` are triggered.
Maybe. Depends if the lack of collision is important for your project.
The solution …

Add actor-player collision in topdown when player not moving

---

appData/src/gb/src/core/UI_b.c

Using ! in dialogue, it is possible to trigger the !S2! speed commands unintentionally, causing missing dialogue, random characters, or the game to get stuck on 1 textbox. Reported on discord.
https://discord.com/channels/554713715442712616/570925559346102273/751042234761085079
If "!" check fails, it prints the character normally as part of a mini else.
Might fix some other slightly weird text cases, but be on the look out for more.
* **Does this PR introduce a breaking change?** (What changes might users need …

Fix !!!! being interpreted as a !S2! command and getting stuck

---

src/components/app/Splash.jsx

Bug fix
#448 #467 #517 Users can not select a project path or are stuck building a project indefinitely.
Something about the tools changed causing webkitdirectory to provide an array of the file contents of a folder, and not the folder itself.
Replaces default file dialogue with 
electron.remote dialouge.showOpenDialogue({ properties: ['openDirectory'] });
Which returns only the path of the selected folder, and is much faster than the method before it was broken.
* **Does this PR introduce a breaking change?** …

Fix Project path selector to select empty folder, not contents of folder

---

appData/src/gb/include/ScriptRunner.h
appData/src/gb/src/core/ScriptRunner_b.c
src/lang/en.json
src/lib/compiler/scriptBuilder.js
src/lib/events/eventIfColorSupported.js
src/lib/events/scriptCommands.js

New feature
Users can't differentiate if the device the game is running supports Color or not. Games with specific color features like animations using palette cycling look bad in non-color devices. Similarly for games that depend in 2xCPU as they'll run very slow in non-color devices.
A new event that checks if the device supports color and runs scripts accordingly. 
No
* **Other …

New event: if device supports color

---

src/store/features/entities/entitiesState.ts

Fix
- [ #528 ] Incorrect variables aren't fixed properly leading to incorrect variables appearing as parameters.
- Variables included in commented events were added to the parameter list (part of #532 bug report)
Fixed the above
No
#532 is about variables still being included as parameters when Switch choices are reduced. That's going to be hard to fix without a) …

Fix a couple of Custom Events bugs

---

src/lib/compiler/compileData.js

Bug fix
Adding any new local variable will force the engine to recompile (60+Seconds), due to TMP_VAR_1 and 2 being indexed at the end of the list, modifying in Data_ptrs.h
INSTANT COMPILES EVERYWHERE!
TMP_VAR_1 and 2 are now added to variable list after the first 100 global variables, so will always be var 101-102, never causing an update when new variables are added.
Can't see how.
* …

Fix instant compile

---

src/store/features/entities/entitiesState.ts
src/store/features/entities/entitiesTypes.ts
test/dummydata.ts
test/store/features/entities/entitiesState.test.ts

Very small fix for #563
Custom Event instances name changes to `EVENT_CALL_CUSTOM_EVENT` when editing the event
Custom Events keep their name
No

Custom Event name incorrectly set on update

---

appData/src/gb/src/states/Platform.c

Fixes a bug where the player in platformer mode would not update its facing direction until a few frames after reversing its direction of movement.
If you walk in a direction in platformer mode, then quickly switch to the other direction, you character will start moving in the new direction, but it will take a few frames for the sprite to change the direction it is facing. This is due to a missing player.rerender = TRUE in the left and right input sections of the script.
The player sprite reverses direction …

Fix platformer direction change rerender

---

src/components/forms/ScenePropertySelect.js

Bug Fix
App shows blank page when trying to select an from the property dropdown (reported in #546)
No crash :)
Nope

Fix crash when selecting property

---

src/components/script/ScriptEditor.js
src/lib/events/index.js
src/lib/plugins/plugins.js

Fix for #567 where javascript functions in events would no longer call due to a previous change in 84a836f9cf5585c804f7e2397f2f75944e88f711
Events have the option of hooking in javascript functions for some functionality (e.g. the updateFn used in text events to limit the amount of text displayed total and per line). Since 84a836f9cf5585c804f7e2397f2f75944e88f711 (including the Beta 3 release) this functionality is broken.
Reverts the previous change in 84a836f9cf5585c804f7e2397f2f75944e88f711 and restores this functionality by moving where the conversion from a VM2 …

Fix for 567, keep event/plugin data as VM2 proxy

---

src/lib/helpers/clone.ts
src/lib/project/loadBackgroundData.js
src/lib/project/loadMusicData.js
src/lib/project/loadProjectData.js
src/lib/project/loadSpriteData.js
src/lib/project/watchProject.js
src/store/features/entities/entitiesState.ts
src/store/features/entities/entitiesTypes.ts
test/dummydata.ts

Attempt to fix issues seen in #574 where renaming assets causes ids to be regenerated and any scenes/events referring to those ids would be broken.
Asset file watching is handled in https://github.com/chrismaltby/gb-studio/blob/v2beta/src/lib/project/watchProject.js using the module [chokidar](https://github.com/paulmillr/chokidar) which handles the complexities of cross platform file watching. In chokidar when a watched file is renamed it fires an unlink (delete) file event followed by an add file event with no way to determine that this was a single rename action (and it looks unlikely that this functionality will change …

Allow renaming project assets while preserving id

---

src/lang/en.json
src/lib/compiler/buildMakeScript.js
src/lib/compiler/makeBuild.js

Replaces the Makefile with a generated Bash script when building the app for Mac/Linux to remove dependencies needed to build a game.
On a Mac building without the full Xcode app or the Xcode Command Line Tools installed throws errors preventing a build from completing, there are also cases where some users have Xcode installed but their specific environment prevents it from working. There is currently a section in the documentation giving a fix https://www.gbstudio.dev/docs/build/#troubleshooting but many people do not find this and ideally GB Studio should not require any third party applications to be installed manually.
* …

Remove xcode tools dependency for Mac by using bash script rather than Makefile

---

forge.config.js
src/PreferencesRoot.js
src/components/app/Preferences.tsx
src/lang/en.json
src/lib/helpers/getTmp.js
src/main.ts
src/menu.js
src/preferences.html
src/styles/App.css
src/styles/Preferences.css

Feature, adds the ability to change tmp directory location
The tmp directory is set automatically using Node's `os.tmpdir()` function with a few overrides to handle long folder paths and detecting if the user used the itch.io app to install (both of which have caused issues in the past). As noted by @RichardULZ in the comments of #592 some users due to their environments do not have the permission to create files and run the compiler from within this folder.
The default tmp directory logic is the same but a Preferences window has been added, accessible from the …

Add preferences window for setting tmp directory

---

src/components/library/Toolbar.css
src/main.ts

Sets a smaller min width on the main window, allowing GB Studio to run maximised on devices with lower resolution screens (such as phones) or allow GB Studio to be tiled on medium resolution screens (such as low-end laptops).
Only medium resolution screens can run GB Studio maximised, and only high resolution screens can tile GB Studio.
Min width of the main window has been adjusted to compensate for lower resolutions, allowing more devices to run GB Studio maximised or tiled.
* **Does this PR introduce a …

Set smaller min width for main window

---

appData/src/gb/src/core/ScriptRunner_b.c
src/lib/events/eventInputScriptSet.js
src/lib/project/migrateProject.js
test/migrate/migrate200releases.test.js
test/migrate/migrateProject.test.js

Allow the same script to be attached to multiple buttons in "Joypad Input: Attach Script To Button".
Inspired by @pau-tomas's pull request #593, I decided to implement the ability to attach the same script to multiple buttons. This could be useful in simpler games where there is only one action assigned to both A and B, or where you'd like to temporarily disable player movement by attaching empty scripts to all the D-Pad buttons, for instance.
You cannot attach the same script to multiple buttons without calling "Joypad Input: Attach Script To Button" multiple times.
* …

Allow the same script to be attached to multiple buttons in "Joypad Input: Attach Script To Button"

---

src/components/script/ScriptEditor.css

Implements enhancement request from #602 
"Display Dialogue" event textarea input uses variable width fonts making it difficult to align how text will appear ingame from the editor
"Display Dialogue" event textarea has been switched to use a monospace font to closer align with ingame appearance.
No

Switch dialogue event text input to use monospace font making it easier to align text in game

---

appData/src/gb/engine_version
appData/src/gb/include/Palette.h
appData/src/gb/src/core/DataManager.c
appData/src/gb/src/core/Palette.c
appData/src/gb/src/core/ScriptRunner_b.c
src/components/forms/PaletteSelect.js
src/components/script/ScriptEventFormInput.js
src/lang/en.json
src/lib/compiler/helpers.js
src/lib/compiler/scriptBuilder.js
src/lib/events/eventPaletteSetBackground.js
src/lib/events/eventPaletteSetUI.js
src/lib/project/ejectEngineChangelog.ts

Implements a request from #591 making the palette select inputs on palette events clearer
As seen in #591 palette events have a default label of "None" with the swatch preview showing the default DMG colors when actually choosing this value would use the scene default colors defined on the Settings page.
The palette update events have been updated to closer match how they work in the Scene editor sidebar. The default label now says "Global Default", the palette number is prefixed before each label, and the swatch preview shows the global palette that would be used. …

Fix "none" value for palette select inputs in palette events

---

src/lib/compiler/compileData.js
src/lib/compiler/helpers.js
src/lib/compiler/scriptBuilder.js
src/lib/helpers/trimlines.js
test/helpers/trimlines.test.js

Fix for edge cases in `trimlines` function used for string trimming to fit character limits.
Since an issue in beta3 prevented input from being trimmed automatically projects could have text that overflows into the background tiles, while the latest dev builds mostly fix this issue if anyone made a broken text event in beta3 it wouldn't be fixed in beta4 until they manually edited the event. There are also a handful of edge cases I've found where variables ($L0$), characters codes (#L0#) and speed codes (!S3!) contribute more characters to totals than they should so cause unnecessary cropping.
* **What is the new behavior (if …

Fix edge cases in trimlines

---

appData/src/gb/engine_version
appData/src/gb/include/Input.h
src/lib/project/ejectEngineChangelog.ts

Fox for #611 - Adventure scene type movement is broken
Regression introduced in 410e6bec5d5b6f279d60fe41109410d5b4ef5bab
Bug fix
Player only moves in diagonal in Adventure mode as reported in #611 
Player can move in any of the 8 directions in Adventure mode
No

Fix movement in Adventure mode

---

appData/src/gb/engine_version
appData/src/gb/src/core/Input.c
src/components/forms/InputPicker.js
src/lib/project/ejectEngineChangelog.ts

Two small fixes for regressions introduced by the recent changes on Attach Script to Button
1) When `Attach Script to Button` doesn't persist across scenes, the override default behavior does. Making default behaviors unavailable in following scenes after attaching a script.
2) `Attach Script to Button` allows for no button to be selected which results on the script being attached to all buttons. Same happens with `Remove Attached Script`, but in that case the script is detached from all the buttons.
1) …

Bugfixes for Attach Script to Button 

---

appData/src/gb/src/core/ScriptRunner_b.c

Bug fix
Timer scripts aren't executed if there's On Update scripts (that don't contain a Wait event) in the scene.
Timer scripts run even when On Update scripts are present.
🤷 I'm not sure of the side effects of the change. But the assumption is that `script_ctxs[0]` is used only for non-background scripts so `On Update` ones are never assigned there.
N/A

Update Timer script even if On Update scripts are running

---

src/lib/compiler/compileData.js

Bug fix
Reported [on Discord](https://discord.com/channels/554713715442712616/585023243732123676/769298433202061364) a project was failing on compile with the following error:
After a bit of debugging, the error was due to a spritesheet field being set to `None` in a commented event in a completely different script from the same scene.
Even if the spritesheet didn't exist, it was added to the scene sprite list with index `-1`. Then, when compiling a call to `Actor: Set Sprite Sheet`, the call to `getSpriteOffset` looks in the global sprite list for a sprite with index `-1`, which is `undefined` and then tries to access `size` …

Don't add sprites to the sprite scene list if not used

---

appData/src/gb/engine_version
appData/src/gb/src/core/Projectiles_b.c
src/lib/project/ejectEngineChangelog.ts

Tiny Bug fix
#506 actors moving up or down have a width of 5 tiles if on grid, instead of 3, due to a value of +-16 each side including equal to. 
#573 Is user error where a player fired projectile can collide with the player.
Reducing to 15 will fix this on grid to 3 tiles horizontally, but is extremely tight in adventure mode.
Reduced a further 3 px each side to 12, assuming projectile with a 2px border each side & Actor having 1px leeway each side, this feels pretty good.
* **Does this PR introduce a …

Reduce projectile collision width to fix #506 & #573

---

appData/src/gb/src/core/Scroll.c

bug fix on the Engine props branch (as this already modifies fade to black)
* **What is the current behavior?** (You can also link to an open issue here) 
#568
A bug from old Fade to black vsync change, where instant camera moves could show 1 frame of garbage.
Force black palette for everything before the re render occurs in scroll.c, bypassing the palette switch.
Not likely.
#625 for engine props/fields pr

Fix instant camera move with Fade to black

---

src/components/library/PaletteBlock.tsx
src/components/world/BrushToolbar.js
src/components/world/SceneCursor.js
src/components/world/World.js

Implements an enhancement request from #656 allowing the currently hovered tile's palette to be highlighted in the palette toolbar.
It's not possible to determine the palette used for a specific tile except by looking at the colour, if tiles use similar palettes or palettes with overlapping colours it may not be possible to tell which palette the tile is using at all.
* **What is the new behaviour (if this is a feature change)?**
When in the colorize mode if you hover over a tile for a short period of time the tile's current palette will be highlighted
In this screenshot the hovered tile is using the second palette (shown by …

Highlight palette under hovered tile. Alt click to switch to that palette

---

CHANGELOG.md
appData/src/gb/engine.json
appData/src/gb/include/Math.h
appData/src/gb/src/core/Actor_b.c
appData/src/gb/src/core/Core_Main.c
appData/src/gb/src/core/Math.c
appData/src/gb/src/core/ScriptRunner.c
appData/src/gb/src/core/ScriptRunner_b.c
appData/src/gb/src/core/Scroll.c
appData/src/gb/src/core/UI.c
appData/src/gb/src/core/UI_b.c
src/components/forms/CustomPalettePicker.js
src/lib/project/ejectEngineChangelog.ts

Bug Fix
Multichoice always picks option 2 when B pressed, some users mistake A and B.
Changing actor speed on attach or mid frame caused issues #629
Emote on simulscript like update not cleared on scene switch
Multichoice no longer uses b for option 2 by default, menu unaffected.
Actor speed events clamp the actor position by 4 pixels, seems to fix the issue for any speed.
Emote sprite 0-1 is cleared on scene start
* **Does this PR introduce a breaking change?** (What changes might users need to make in their …

Fixing beta5

---

package.json
yarn.lock

While testing GBS 3, I noticed that none of the copy+paste behavior worked as-intended
After doing a bit of debugging, I saw that `readBuffer` wasn't giving a proper output after the data was being stored 
It turns out this was an upstream bug in the version of Electron we were using:
https://github.com/electron/electron/issues/24253
And a fix was published in version `8.4.1`:
https://www.electronjs.org/releases/stable?version=8&page=2#8.4.1
No copy+paste action worked on Windows
Copy+paste now works in …

[v3] Fix clipboard on Windows

---

.gitignore
package.json
src/main.ts
yarn.lock

While working on debugging #764, I wanted to see if the Redux store was firing the action I expected it to. While `console.log` _works_, it was nice to see the store actions being fired when I was working on them.
I then realized that I would run into this issue in the near future if/when I end up working on some UI work. I thought it'd be nice to enable those two developer tools by default when running in dev mode. This PR adds that functionality
That said, I know this isn't a high priority. No worries in the slightest if this PR is rejected - I'd entirely understand. :)
* **What is the current behavior?** (You can also link to an open issue …

[v3] Enable developer tools in debug mode by default

---

test/data/compiler/compileEntityEvents.test.js
test/data/compiler/scriptBuilder2.test.ts
test/dummydata.ts

This PR helps fix ~7-8 tests we had that were not passing the proper `font` data, thus introducing failing tests. They originally failed and looked like this:
But now pass as-expected
This PR fixes said tests
N/A
No
I noticed there's still a failing text codegen test after this change, but it seems to be due to a changed number in the string output:
Is this …

[v3] Fix font codegen tests

---

src/components/world/Scene.js

> I have done manual bug testing, but am not yet aware of how to do integration testing with GBS itself. I have done things like `react-testing-library` in past projects. Do we have something like that setup?
Bug fix
If you have a scene in a GBS with an invalid `backgroundId`, say from setting an image file then deleting it, reopening GBS will throw an error and refuse to load any of the UI.
Now, when loading a project w/ invalid scene background, the behavior is more consistent w/ GBS 2 beta, where the …

[v3] Fix regression behavior when invalid background present

---

src/components/world/SceneCollisions.tsx

This PR refactors the `SceneCollisions` component to use TS & functional hooks
N/A
There should be no behavioral changes after this PR.
No
This PR was made as part of an effort to migrate Scene-related components to TS/FC after running into a regression that was fixed in #776
The other components I want to tackle before working on Scene would be:

[v3] SceneCollisions TS migration

---

src/components/script/MenuPreview.tsx
src/components/script/ScriptEditorEventHelper.tsx
src/components/script/TextPreviewHelper.ts
src/lib/compiler/compileData.js
src/lib/compiler/scriptBuilder.ts
src/lib/events/eventMenu.js

Feature
Menu events don't have a preview like the dialogue events do. Also, menu items are limited to 6 characters.
Menu events now have a preview when selected. The character limit has been removed as the preview displays (more or less) when the menu will look broken in-game.
"more or less" because the preview doesn't take into account if the game runs on DMG or not and the tile limit for text is different based on that so, in some cases, the preview and the game will not match as the text will overflow …

Add preview view to menu event

---

README.md

* **Other information**: 
3.0 documentation is out and (imo) appropriately complete for the new version. This disclaimer isn't needed anymore.

Remove README line about outdated documentation

---

src/lib/project/watchProject.js

Bug fix!
Assets added after project launch are not watched or updated, 
My best guess, chokidar watch latest update made the regular expressions exclude folders from the watch path?
Use globs instead of regular expression for file type
Using path/**/.uge to search all subfolders with exact extension.
Tested on windows in live development build
uiRoot and sgbRoot now have lower and upper …

Fix assets not being watched or live updating from chokidar

---

src/lib/helpers/eventSystem.js

Bug fix
When event fields where inside a group of fields (ie: `x` and `y` in `Move Actor To`) the property fields weren't not being properly detected inside custom scripts and the actor associated to the property wasn't being added to the parameters list.
The `isPropertyField` function looks recursively for the field if there's a field group in the event.
No

Properly detect grouped property fields for events inside custom scripts

---

CHANGELOG.md
appData/wasm/binjgb/js/script.js

Bugfix
Reported on discord. Emulator appears blurry on Desktop Safari.
This is due to https://bugs.webkit.org/show_bug.cgi?id=193895
Use Canvas2DRenderer on Safari Desktop until is fixed
No
The user agent detection is a bit narrow (detecting only Safari 15.0 to 15.9) but hopefully the bug will be fixed soon 🤷

Fix blurry emulator on Desktop Safari

---

CHANGELOG.md
src/components/ui/form/MathTextarea.tsx
src/lib/compiler/scriptBuilder.ts

Bug fix
Inside a custom script:
- When clicking in a variable within a math expression textarea and selecting a new one the variable is added as `$00$` which isn't a valid variable inside a custom script and not detected as a parameter (reported as a follow up for #918 )
- Variables within math expressions aren't correctly parsed in codegen leading to unexpected results (tl;dr - codegen isn't using `R_REF_IND` when referencing the arguments inside `VM_RPN`).
Fixed the above bugs
* **Does this PR introduce a breaking change?** (What changes might users need to make …

Fix bugs with custom scripts and math expressions

---

CHANGELOG.md
src/lib/events/eventActorShow.js

I was looking at the code to get some understanding of GBVM and noticed eventActorShow was missing a label as opposed to eventActorHide. I just added it back.

[Events] Add missing actor label in eventActorShow.js

---

CHANGELOG.md
src/lib/helpers/uge/ugeHelper.ts

Bug fix
Version 5 of the uge file format uses unique keys to reference each pattern, those keys aren't consecutive like in previous versions. 
GB Studio is skipping those patterns and using a consecutive id instead meaning that some uge files created with hUGETracker can't be opened with GB Studio because the patterns referenced in the sequence order *by key* have a different id when generated in GBS. #1006  is an example of this.
To make it worst. uge songs saved with GBS have a, related but different bug, where the pattern key is always set to `0`, `1, `2` and `3`... meaning that those files can't be open with hUGETracker …

Use pattern key when loading/saving uge files

---

CHANGELOG.md
src/components/music/helpers/player.js

Bug fix
Wave preview fails because no waveforms are passed to the function
If no waveform are passed to the function use the current song waveforms. The parameter waveforms are only used for previewing from the instrument editor as they might be changed there.
No

Fallback to current song waveforms in song preview

---

src/lib/helpers/eventHelpers.ts

Fix
App crashes when navigating to a script that uses a plugin event that doesn't exist anymore due to the `waitUntilAfterInitFade` and `allowChildrenBeforeInitFade` being check in an undefined object.
Mark the plugin event as optional so it doesn't crash.
No

Fix crash when plugin event not found

---

CHANGELOG.md
src/components/forms/PaletteIndexSelect.tsx

This commit adds a convenience feature to the sprite palette select for sprites by using the "real name" of the palette instead of just "Palette N"
When listing the available palettes for coloring a sprite, it shows a list of "palette N" 
The list now uses the name of the palette (eg : default sprites) 
* **Breaking changes ?**
No, afaik

Improve palette select for sprites by using the "real name"

---

src/lib/compiler/compileData.js

bugfix
Compile fails when trying to display a warning when precompiling images
Removed an unused parameter to fix the issue
No
N/A

Fix `TypeError: warnings is not a function`

---

CHANGELOG.md
appData/src/gb/src/core/projectiles.c

Bug fix to the `projectiles.c` file. The previous logic missed a scenario where projectiles greater than 224 degrees fell into the `(angle > 96)` condition.
Tweak the projectile logic when setting the correct frame based on angle.
Projectiles between 224 and 360 degrees point down.
Projectiles between 224 and 360 degrees point up.
No

Projectiles from 224 to 360 degrees now look up

---

src/components/script/AddScriptEventMenu.tsx
src/lib/compiler/compileData.js
src/lib/compiler/scriptBuilder.ts
src/lib/events/index.ts
src/lib/project/loadProjectData.js
src/lib/project/migrateProject.js
test/data/compiler/compileEntityEvents.test.js
test/data/compiler/scriptBuilder2.test.ts
test/migrate/migrate300releases.test.js
test/migrate/migrateProject.test.js

Bug fixes
As reported in #1146 there are a number of issues migrating projects from 3.0.0 to 3.1.0 alpha0
- Fix issue causing crash when adding events if any plugin event contains a string for the `groups` value
- Default migrated variable symbols closer match v3.0.0 to improve compatibility with GBVM scripts
- Fix broken actorInvoke event
- Fix an issue where some custom scripts were not being compiled
- Fix an issue where projects created on Mac/Linux would reload assets within folders (and create new ids) if project was created in Windows (need to confirm this …

Fixes for #1146

---

src/components/music/InstrumentNoiseEditor.tsx
src/components/music/SongEditorToolsPanel.tsx
src/components/music/SongTracker.tsx

Bugfix
- Clicking on 7 bit counter field enables length in noise instrument editor
- Octave offset not applied to note preview on tracker view
Fixed the above
Nope

Various tracker fixes

---

src/components/forms/PropertySelect.tsx
src/lib/events/eventActorMoveTo.js
src/lib/events/eventActorSetPosition.js
src/lib/events/eventCameraMoveTo.js

Bug fix?
Even if `$self$xpos` is the default value for the events that include a property selector (like the x and y fields of the move to events) there's no option to pick a property for `self` in the selector so the selector ends up defaulting to player.xpos.
This, for example, means that when trying to do a follower script (where an actor follows the player), the selector for the X field shows the player spritesheet and `Tile X` by default but the event is using `$self$:xpos` 
```
{
"command": "EVENT_ACTOR_MOVE_TO",
"args": {
"actorId": "$self$",
"x": {
"type": "property",
"value": "$self$:xpos"
},
"y": {
"type": …
```

Add $self$ to property select list

---

CHANGELOG.md
src/components/music/helpers/player.js
src/main.ts

Bug fix & feature
Noise preview will use the first position in the macro, and break when playing out of range notes, doesn't sound like the real song at all.
No length notes would preview for 3 seconds, since there's no stop on mouse/key up, this got obnoxious. 
Windows developers could not open the DevOps window for music process due to an electron issue.
Noise macro will now (crudely) preview when placing a note, javascript timings may vary leading to inaccuracies, but it's way better than no preview and …

Add noise macro preview for music editor

---

src/components/music/InstrumentSelect.tsx
src/components/music/SongEditorToolsPanel.tsx

New feature or bug fix depends on how you look at it :)
Instrument Selector lists all the instruments as `Instrument n` not respecting the given instrument name. This is ok for the tracker view because there's no way to select a specific channel and it's impossible to know what specific instrument/channel combination is being used. However in piano roll only one channel is selected at a time so the instruments could be showing its proper name.
In piano roll the names in the instruments select change to match the instrument name for that channel.
* **Does this PR …

Use channel specific instrument names on instrument select dropdown

---

src/bin/gb-studio-cli.ts
src/lib/project/engineFields.ts

Bugfix
local `engine.json` not found when edited in an ejected engine
Fixed the path generation for the local `engine.json` path
No

Fix local engine.json path reading

---

src/lib/events/eventActorSetPosition.js

Fixes issue where setting an actor's position to another actor's X/Y coordinates causes the second actor to move instead of the first.
Setting an actor's position to another actor's X/Y coordinates causes the second actor to move instead of the first. I believe variableSetToProperty is overwriting which actor is active, so calling actorSetActive before variableFromUnion was ineffective.
Setting an actor's position to another actor's X/Y coordinates now works as intended.
* **Does this PR introduce a breaking …

Fix setting actor's position to another actor's position

---

.circleci/config.yml
src/components/library/Alert.css
src/components/library/Alert.js
src/components/music/InstrumentDutyEditor.tsx
src/components/music/InstrumentNoiseEditor.tsx
src/components/music/InstrumentSubpatternEditor.tsx
src/components/music/InstrumentWaveEditor.tsx
src/components/music/SongEditor.tsx
src/components/music/SongPianoRoll.tsx
src/components/music/helpers/player.ts
src/lang/en.json
src/lib/helpers/uge/ugeHelper.ts

Bug fixes
A set of bugs reported by Tronimal with the new uge v6 support
Fixes:
- Write empty subpatterns to song preview rom to avoid change on the memory address of patterns and orders that were causing playback preview not working when disabling or enabling subpatterns for an instrument
- Fix empty effect rendering in subpatterns (use 000 instead of 05A)
- Fix crash when clicking the rightmost line of the grid
Temp changes:
- Show message about note/instrument preview maybe incorrect when subpattern enabled
- Hide noise macro editor for now
* **Does this PR …

Fixes for UGE v6 support

---

appData/src/gb/Makefile.common
src/lib/compiler/buildMakeScript.js

Fix
Compiling to pocket fails with a ```Error: ../_gbstools/gbdk/bin/lcc: old "gbz80" SDCC PORT name specified (in "-mgbz80:ap"). Use "sm83" instead. You must update your build settings.``` message
Compiling to pocket works
No

Fix compile to .pocket

---

src/lang/pl.json

Update of the pl.json, so it will be up to date together with en.json this is the newest update.
Update of translation
Missing lines
Added missing lines
No
This is the updated version of pl.json, that also include the "[Update replace tiles events to allow 16px tiles] - [6d118c1](https://github.com/chrismaltby/gb-studio/commit/6d118c1d5795126bcc8cbb2b49204316d1329 …

Update pl.json [05.04.2024 - ver 1391]

---

appData/src/gb/engine.json
src/lib/project/ejectEngineChangelog.ts
src/lib/project/sceneTypes.ts
src/store/features/engine/engineState.ts

Bug fix
A project that has an ejected engine with an engine.json without the default scene types then no scene type appears in the scene type selector or be compiled and then the rom will crash immediatly on start.
Default scene types will always be used if not scenes types exist in the engine.json
No

Use default scene types if there's none in engine.json

---

src/components/music/WaveEditorInput.tsx

Fix
Pressing "e" doesn't work on the Wave editor field 
"e" works
No
🤦

Fix: Pressing "E" doesn't work on Wave editor field

---

src/lib/project/migrateProject.ts
src/store/features/entities/entitiesState.ts

Fix
New scripts are created with empty name. This used to be replaced with a default name (`Script n`) in the navigation sidebar, but now they're appearing as empty.
Scripts are now created with a default name, and old scripts with empty name are migrated to have a name instead of empty string.
No
Opted by creating the scripts with default name moving forward (instead of an empty string). The other option was map the …

Fix empty title in Script navigator sidebar

---

src/components/forms/FlagSelect.tsx
src/components/script/ScriptEventFormInput.tsx
src/lib/project/migrateProject.ts
test/migrate/migrate400releases.test.js

Fix for #1407
The new flag select field in 4.0 returns a string instead of a number which is what the If Flag Set event expects. This meant that the comparison was always failing.
Make the flag select return a number and migrate any flag value that has been set to a string.
No

Use number for flag field on if flag set event

---

CHANGELOG.md
appData/src/gb/include/vm_gameboy.h
src/lib/compiler/buildMakeScript.ts
src/lib/compiler/makeBuild.ts

Fix / Feature
The VM_RUMBLE command works only with the insidegadgets MBC3 carts with rumble ([they’re out of stock](<https://shop.insidegadgets.com/product/gameboy-4mb-32kb-fram-mbc3-with-rtcrumble-plus-2x-2mb-mode-flash-cart-build-it-yourself/>)). Because those carts also had RTC they operated slightly different than the “official” rumble carts like Pokémon Pinball.
This is what the IG page says about those carts ```How to use the rumble motor
You need to write the byte 0x20 to 0x4000-0x5FFF. Usually games write 0x08 but that would conflict with the RTC so you need to patch games to use 0x20 instead. ```. 
`0x20` is what the …

Update the engine to support rumble for mbc5 carts

---

src/shared/lib/entities/entitiesHelpers.ts

Fixes one remaining issue from #1433 where "DMG (GB Default)" string was still showing up in English.
"DMG (GB Default)" string shows up in the tooltip (title) in the brush tool bar.
String is localized.
No
None
QA results after fix:
Source:
Target:

Fix remaining unlocalized string from issue #1433

---

forge.config.js

Adds "linux" to the maker-zip target so it will allow building on generic Linux.
It refuses to build maker-zip on Linux, hence my hacky fix in the [gb-studio-git](https://aur.archlinux.org/packages/gb-studio-git) package.

add "linux" to maker-zip target for building generic linux binaries

---

src/lang/pl.json

Update for pl.json, added new missing lines regarding FIELD_CART_BATTERYLESS that were recently added.
Update of translation
Missing lines for FIELD_CART_BATTERYLESS
Added missing lines
No
As always regards, and good day.

Update pl.json [1493 05/07/2024]

---

src/lang/en.json
src/menu.ts

Add an entry for the minimize menu in the "en" lang file and reference it into the menu.ts code
Bug fix
Minimize menu is not localized
Minimize menu has in own entry in the lang file
No

Add missing localization for Minimize menu

---

CHANGELOG.md
src/app/project/initProject.ts
src/components/debugger/DebuggerBuildLog.tsx
src/components/debugger/DebuggerUsageData.tsx
src/lang/en.json
src/lib/compiler/romUsage.ts
src/main.ts
src/renderer/lib/api/setup.ts
src/store/features/buildGame/buildGameMiddleware.ts
src/store/features/debugger/debuggerState.ts

feature
Other than looking at the size of the compiled rom for the game there's no way to know the size of the it. Additionally since the rom size grows in "steps" there has been confusion about the real size of the game and when it'll grow to the next rom size.
This change adds a rom usage visualization to the build log panel. The visualization appears and gets updated after each build of the game and includes a way to see the different steps (128 KiB, 256 KiB, 1 MiB, 2MiB and 4MiB) and how much the rom needs to grow to get to the next step size.
* **Does this PR …

Add ROM usage visualization to build log

---

CHANGELOG.md
src/lib/compiler/scriptBuilder.ts
src/lib/events/eventScenePopAllState.js
src/lib/events/eventScenePopState.js

Feature
The Restore Previous Scene and Restore First Scene events don't have the option for an instant transition like Scene Change event.
Added the Instant option
No

Add Instant fade speed to scene pop events

---

forge.config.js

Linux packages require additional configuration in order for the desktop icon to be correctly set[^1].
Fixes #936
[^1]: https://www.electronforge.io/guides/create-and-add-icons#linux

Set icon for deb and rpm packages

---

CHANGELOG.md
src/lib/compiler/compileData.ts
src/lib/compiler/generateGBVMData.ts
test/compiler/generateGBVMData.test.ts

Add animation states to the game_globals.h file (not just the game_globals.i file) so that they can be referenced in engine code.
Animation states are currently only in game_globals.i file, so to be able to refer to them in engine code you have to manually create the defines. However using this method, somtimes the animation states values change and you have to recreate the defines by copy pasting from the game_globals.i file everytime that happens.
This will add the animations state includes in the game_globals.h file which can be referenced in engine code without …

Add Animation States To Global Header File

---

CHANGELOG.md
src/components/settings/EngineFieldsEditor.tsx
src/shared/lib/entities/entitiesTypes.ts
src/shared/lib/resources/types.ts
src/store/features/entities/entitiesState.ts

Bug fix
If a plugin sets an engine field to type "checkbox" the game will not compile with an `?ASlink-Warning-Undefined Global 'true' referenced by module ''` error.
It allows for checkbox type to be used as engine field.
No. People has been using some alternatives for this case (like 0-1 slider on [Belt Scroller](https://github.com/shin-gamedev/gbs-belt-scroller/blob/main/Belt%20Scroller%20Plugin/engine/engine.json#L8) or a Select on …

Fix checkbox not working on engine fields

---

src/lang/pl.json

Added line for open build folder on export.
Missing one line for "Open build folder on export"
Added missing line
Nope.
Merge ASAP, as always - Thank you!

Update pl.json 2052 - open build folder on export
