chrismaltby/gb-studio

- appData/src/gb/include/ScriptRunner.h
- appData/src/gb/src/ScriptRunner.c
- appData/src/gb/src/ScriptRunner_b.c
- src/components/script/ScriptEditor.js
- src/lib/compiler/compileEntityEvents.js
- src/lib/compiler/eventTypes.js
This feature implements a Actor script for conditionally testing a Actors current direction.
This pull request partially solves issue #33
> Implements Actor Script direction testing

- .circleci/config.yml
- README.md
This PR implements a configuration for building the develop branch in CircleCI.
It also adds links in the README.md which always points to the latest develop builds.
Feel free to contact me if you have any questions regarding CircleCI.
> Implement CircleCI

- .github/ISSUE_TEMPLATE.md
This PR adds a Issue Template to make Issues more maintainable
> Add Github Issue Template

- src/lib/compiler/makeBuild.js
Patches the ROMS checksums after modifying the headers.
If not done, the produced ROM will not boot on real hardware.
> Patch ROM checksums

- appData/src/gb/src/ScriptRunner_b.c
- src/lib/compiler/compileEntityEvents.js
There was a bug in the implementation of the relative positioning.
the y axis was using the value for the x axis, and the offset was always too big.
> Fix Relative Actor positioning

- src/actions/index.js
- src/components/world/World.js
- src/reducers/editorReducer.js
- src/windows/projectRoot.js
Lets you zoom using CTRL + Mousewheel,or using touchpad gesture
Fixes #17 
Fixes #40
Partially fixes #101
> Implement scroll zoom

- appData/templates/blank/project.gbsproj
- appData/templates/gbhtml/project.gbsproj
- src/lib/project/createProject.js
Populate a new projects "author" field with the current users username
> Set project author from username

- README.md
> Fixed linux links

- src/lang/pt-PT.json
Several new terms were fixed or added to match the current dev version.
> Updated new terms on pt-PT.json

- package.json
- src/components/app/Splash.jsx
- src/lang/en.json
- src/lib/helpers/l10n.js
- src/lib/helpers/updateChecker.js
- yarn.lock
Checks if a new release is available and redirects the user to the download page.
> Add update check

- src/lang/pt-PT.json
There was a missing brace and comma that was making the script fail. At lines 335 and 320.
> ATTENTION: Corrected missing }

- src/lang/pt-PT.json
This patch adds translations for new terms:
```
"DIALOG_SAVE_CHANGES": 
"DIALOG_SAVE_WARNING": 
"DIALOG_SAVE": 
"DIALOG_DONT_SAVE":
```
No.
> Updated missing terms on pt-PT

- src/lang/pt-PT.json
New term added and translated:
`"EVENT_ACTOR_SET_FRAME_TO_VALUE": "Actor: Set Animation Frame Using Variable",`
No.
> Updated pt-PT.js

- src/lang/pt-PT.json
Added missing translations for:
```
"NAV_SETTINGS": "Settings",
"FIELD_RESTORE_DEFAULT": "Restore Default",
"FIELD_ORIGINAL": "Original",
"FIELD_CUSTOM": "Custom",
"MENU_SETTINGS": "Settings",
"// 16": "Settings ----------------------------------------------------",
"SETTINGS": "Settings",
"SETTINGS_SCENES": "Scenes",
"SETTINGS_SCENE": "Scene",
"SETTINGS_ACTORS": "Actors",
"SETTINGS_ACTOR": "Actor",
"SETTINGS_CART_TYPE": "Cartridge Type",
"SETTINGS_CONTROLS": "Controls",
"SETTINGS_COLORS": "Colors",
"SETTINGS_CUSTOM_HEADER": "Custom Header (Web Build)",
```
* **Does this PR introduce a breaking change?** (What changes might users need to make in …
> Updated pt-PT.json localization

- src/lang/pt-PT.json
Added Portuguese missing translations for:
```
"FIELD_FLAG_1": "Flag 1",
"FIELD_FLAG_2": "Flag 2",
"FIELD_FLAG_3": "Flag 3",
"FIELD_FLAG_4": "Flag 4",
"FIELD_FLAG_5": "Flag 5",
"FIELD_FLAG_6": "Flag 6",
"FIELD_FLAG_7": "Flag 7",
"FIELD_FLAG_8": "Flag 8",
"EVENT_SET_FLAGS": "Variable: Set Flags",
"EVENT_ADD_FLAGS": "Variable: Add Flags",
"EVENT_CLEAR_FLAGS": "Variable: Clear Flags",
"EVENT_IF_FLAGS_COMPARE": "If Variable Has Flag",
```
No.
> Updated pt-PT localisation

- src/lang/pt-PT.json
Adds Missing translations for:
```
"CUSTOM_EVENT": "Custom Event",
"SIDEBAR_CUSTOM_EVENT_SCRIPT": "Custom Event Script",
"SIDEBAR_CUSTOM_EVENTS": "Custom Events",
"SIDEBAR_CREATE_CUSTOM_EVENT": "Create Custom Event",
"SIDEBAR_PARAMETERS": "Parameters",
"FIELD_DESCRIPTION": "Description",
"FIELD_FREQUENCY": "Frequency in hz",
"FIELD_DURATION": "Duration in seconds",
"FIELD_PITCH": "Pitch",
"FIELD_SOUND_PLAY_CRASH": "Play crash symbol sound",
"FIELD_SET_TIMER": "Set repeating timer script",
"FIELD_TIMER_DURATION": "Countdown time in seconds",
"FIELD_TIMER_RESTART": "Restart the countdown timer",
"FIELD_TIMER_DISABLE": "Disable the timer script", …
```
> Updated pt-PT language localization

- src/reducers/entitiesReducer.js
Fixes bug where Custom Event variables where still rendered in dialogue even after removing them from the parameter list.
Bug fix
- Create a new Custom Event, add any Event referencing a variable (for example `Variable: Decrement by 1`) and then a `Dialogue` Event referencing that variable.
- Add the Custom Event to a Script and set the parameter variable to a variable with a value different than 0.
- Edit the Custom Event and remove the `Variable: Decrement by 1` Event, but keep the dialogue one.
- Run the project. When the Script is executed the dialogue will still render the variable value.
* **What is the new behavior (if …
> Cleanup Custom Event instance args after editing

- src/lib/compiler/scriptBuilder.js
Bug fix
Variable rendering (`$XX$`) doesn't work on Choice and Menu Events. Variables always render as `0`.
Variable rendering works on those events.
Couldn't ran tests locally on my current laptop. Some of them might be failing.
> Replace variables on menu and choice event strings

- src/reducers/entitiesReducer.js
Added a path in updateEntitiesCustomEventScript to update startScript on actors and triggers when needed.
When a Custom Event script was updated the instances of it in Init Scripts (for actors and triggers) weren't updated accordingly.
Instances of Custom Events on Init Scripts should be updated.
No breaking change. But users affected by the bug should manually do a dummy update of their …
> Update Custom Event instances in Init scripts

- src/lib/events/eventVariableSetToValue.js
- test/events/eventVariableSetToValue.test.js
* **What kind of change does this PR introduce?**
Bug fix, Optimization
* **What is the current behavior?**
Variable Set to Value will send nan / null data if 0 is not typed in, despite defaulting to 0...
https://discordapp.com/channels/554713715442712616/570925559346102273/702357708073992243 
If value is greater than 1 use value command,
If value = 1, set true command (faster),
Else, (0 or no value), set false command.
No more Null error message (because we check all the data now).
User also notes music compile is slow, but …
> Fix Variable Set to Value causing Nan / Null if no value (and optimize)

- src/lang/pt-PT.json
Updated 'Errors column' with:
`"ERROR_PLEASE_SELECT_A_DIFFERENT_LOCATION": "Please select a different location",`
No!
> Updated pt-PT

- src/lib/compiler/scriptBuilder2.ts
Very small change that adds store actor position into variables to the 3.0 codegen
> Add actorGetPosition to codegen

- src/components/settings/ColorAnimationText.tsx
- src/containers/pages/SettingsPage.tsx
A small easter egg
There's no easter egg
Something happens when you do something
I hope not
> Just a small silly thing

- src/components/music/InstrumentNoiseEditor.tsx
- src/components/music/NavigatorSongs.tsx
- src/components/music/NoiseMacroEditorForm.tsx
- src/components/music/SongPianoRoll.tsx
- src/components/music/SongTracker.tsx
- src/lib/helpers/uge/ugeHelper.ts
- src/store/features/trackerDocument/trackerDocumentTypes.ts
Bug fix
Uge v5 songs (the default version when saving fron hUGETracker) aren't loading correctly in GBS. 
V5 songs should load correctly. Old format versions will also load and will be saved in v5 when modified. 
No
> Uge v5 fixes

- src/store/features/entities/entitiesState.ts
Bug fix
Variables inside Math Expressions aren't detected in Custom Scripts #918 
Variables are detected :)
No
> Custom Scripts: Detect variables in math expression events

- src/lib/helpers/uge/ugeHelper.ts
Bug fix
Wave length is saved incorrectly (#924)
Wave length to save correctly 
No
> Fix error when saving wave length

- src/lib/compiler/scriptBuilder.ts
Bug fix
Link Close codegen wasn't implemented and failed at compile time
Link Close codegen implemented
No
None of the link events is documented and it's behavior it's a bit obscure. We should review those and have some good practices for link cable usage.
> Add link close codegen

- CHANGELOG.md
- src/components/editors/TriggerEditor.tsx
Fix for Trying to replace "On Leave" script on trigger replaces "On Entry" instead #960
> Pass script type to trigger editor dropdown menu

- src/app/music/MusicRoot.js
- src/components/music/InstrumentWaveEditor.tsx
- src/components/music/SongEditor.tsx
- src/components/music/helpers/player.js
Bug fix
- Instrument name isn't editable
- Ticks per row field updates aren't reflected when playing the song
- Wave form changes are not updating for instrument preview
All the above fixed
No
N/A
> A bunch of bug fixes for the tracker

- src/lang/pl.json
Alright, proper version of the file, added translations for hide/show actor, and also translated few other lines that showed up.
Now it is as en.json - good to go.
Update of translation.
Missing few lines.
update of translation so it will be the same as en.json.
no.
-
> Update pl.json // 896

- src/components/music/RollChannelEffectRow.tsx
- src/components/music/SongPianoRoll.tsx
- src/components/music/SongTracker.tsx
- src/components/music/helpers.ts
- src/store/features/trackerDocument/trackerDocumentState.ts
Improvement
Could not see the new effect editor in tracker view, 
Placing a new effect in piano roll would default to 000.
New
Copying a selection was not ModPlug compatible
Pasting a partial selection overwrote other parameters
Selecting any effect column in tracker will open the effect editor
Placing an effect in piano roll will keep the last selected effect data for quick placement (or 0)
New
Copying a selection includes spaces for non overwriting selection and is ModPlug compatible
```
GBStudio hUGETracker …
```
> Tracker fixes and improvements for effects and pasting

- src/app/music/MusicRoot.js
- src/components/music/helpers/player.js
- src/store/features/music/musicMiddleware.ts
Bug fix
UGE Songs couldn't be previewed from the Play Music event 
Fixed
Nop
> Fix preview of uge songs from Play Music event

- src/lang/pl.json
Updated pl.json translation so it will be up to date.
Update missing words from 23.11.2023
Missing translations
Adds missing translations
no
As always update so it will be the same as en.json
> Update pl.json (23.11.2023)

- appData/src/gb/include/gbt_player.h
Fix for #131 
Game crashes when playing a mod file
Game doesn't crash
> Fix GBT_player crash with the new GBDK-2020

- src/app/music/MusicRoot.js
- src/components/music/UgePlayer.tsx
- src/shared/lib/music/types.ts
- src/store/features/music/musicMiddleware.ts
- test/__mocks__/apiMock.js
- Set song as non-optional for both play and load song as player.ts expects them like that
- Removed ipcRendered dependency in musicMiddleware and use the API
- Changed signature of the muted action for consistency
> Cleanup of Music API

- CHANGELOG.md
- src/components/forms/ParallaxSelect.tsx
- src/components/ui/util/HighlightWords.tsx
- src/lib/compiler/scriptBuilder.ts
- test/store/features/debugger/deguggerState.test.ts
- test/store/features/navigation/navigationState.test.ts
Small fixes
- Last parallax layer has always a fixed height in the UI
- Add event autocomplete crashes when using some characters like [ or \
- Compile was crashing when While event used "!" in the new script value fields
- "Should switch to build page on any console errors" test fails as Build page doesn't exist anymore
Fixes all the above 
No
> Some small fixes

- src/lang/pl.json
Update of the pl.json file so it will be up to date.
Update
Missing lines
No.
-
> Update pl.json (24/04/2024)

- src/lang/pl.json
New update for pl.json, where new lines were added so it will match en.json as always.
missing lines
added missing lines
No, should not.
Thank you as always for fast merge (((/\\^)
> Update pl.json [1470 09/05/2024]

- src/lang/pl.json
Update of the pl.json file, adding translation for 70d3e2e
update of the translation
missing lines
Added lines
No.
...
> Update pl.json [1488 ]

- src/lang/pl.json
Update of the pl.json file so it will be up to date. Added missing new lines.
Update
Missing new lines
Added new missing lines together with translation
Nope.
Good day as always, waiting for PR to be merged.
> Update pl.json [1490] - 04/07/2024

- appData/templates/blank/assets/tilesets/README.md
- appData/templates/gbhtml/assets/tilesets/README.md
- appData/templates/gbs2/assets/tilesets/README.md
Very small thing, but there have been some questions in the discord server about where to put the tilesets.
> Add "tilesets" folder to sample projects

- src/lang/pl.json
Small update for pl.json, added new lines (about script uses) that were included in the https://github.com/chrismaltby/gb-studio/commit/e8d8cd53b0db2a12ee7c53c52d464342e0cb3298
update translation
missing lines
added new lines
No.
Please remember also about the PR for the DOCS.
> Update pl.json (1498240812) e8d8cd5

- src/lang/pl.json
Update for pl.json translation, 
added new lines from https://github.com/chrismaltby/gb-studio/commit/1d3f42edf470312e1c706a116bf47a3fecc99643
Missing new lines
Added missing lines
No.
> Update pl.json [1505-15/08/2024]

- src/lang/pl.json
Update for the pl translation.
Added lines from collision and text sound effect.
Translation update
Missing lines for set collision as well as set sound effect in text.
Added translation for missing parts
No.
As always thank you for fast merge.
> Update pl.json [1513 16/08/2024]

- src/lang/pl.json
Update pl.json for another lines.
Update for translation.
Missing new lines
No.
Thank you for fast merge.
> Update pl.json 1545

- src/lang/pl.json
Update for PL translation, added new line from the PR: https://github.com/chrismaltby/gb-studio/commit/a75db8b6365c9068f6e302b949746072a72697cf
Update for the pl.json
Missing line
Added new line
No.
AS always please for fast merge, thanks!
> Update pl.json 1752 (COMPILER_USING_ENGINE_PLUGIN)

- src/lang/pl.json
Update for pl.json, added lines for printer, that were mention in https://github.com/chrismaltby/gb-studio/commit/04c01b13d89d00d933b15d3d9469f980c4d5551c
Missing lines that were included in https://github.com/chrismaltby/gb-studio/commit/04c01b13d89d00d933b15d3d9469f980c4d5551c
Missing lines are translated
No
Keep up the good work (((/\\^)
> Update pl.json 1653 (printer terms) - 04c01b1

- src/lang/pl.json
Update for pl.json, added lines from for camera, mention in  e045014
Update another...
Missing lines
no
Another update, as fast as possible - merge, thank you (((/\\^)
> Update pl.json 1661 ( added camera lines - e045014 )

- src/lang/ja.json
Update ja.json localized key for string "remove from recent list" (SPLASH_REMOVE_FROM_RECENT) [df420d0]
> Update ja.json localized key for remove from recent

- src/lang/pl.json
Updated for pl.json, added missing line for warning for background.
Update
Missing line
Added new line
No.
As always, please make a fast merge. 
If something will be added, I will try to update as fast as possible
Thanks (((/\\^)
> Update pl.json 1681 (added warning for background)

- src/lang/ja.json
Update ja.json localized key for invalid background [29002be]
> Update ja.json localized key for invalid background

- src/lang/pl.json
Update for pl.json, added missing lines for Constants.
Update
Missing lines,
Added missing lines
No
Merge fast as always, thank you.
> Update pl.json 1694 (add Constants and error reports)

- src/lang/pl.json
Missing lines
No
As always please and thank you for fast merge!
> Update pl.json [1766] (added layer opacity)

- src/lang/pl.json
Update for the translation
Missing few lines
No
As always thank you for fast merge.
> Update pl.json 1769

- src/lang/pl.json
Missing few lines
Added missing lin es
Nope.
Thank you for fast merge as always.
> Update pl.json 1773

- src/lang/pl.json
Missing translation for Wait untill key pressed
Added missing line
This time no <(((-^)"
Thanks.
> Update pl.json 1774 (added: wait for press)

- src/lang/ja.json
FIELD_WAIT_UNTIL_BUTTON_PRESSED label localized.
> Update ja.json localization for 40f6457

- src/lang/pl.json
Added additional missing lines
Missing lines
Added 2 missing lines
No.
As always, please add as soon as possible. Thank you.
> Update pl.json 1784

- src/lang/ja.json
Update ja.json localization for Audio settings [fdf7301fa]
> Update ja.json localization for Audio settings [fdf7301fa]

- src/lang/pl.json
Update for the pl.json translation. Added missing lines for camera lock options.
Update for the pl.json
Missing few lines
Added translation for missing lines
no.
Merge as always asap. Thanks!
> Update pl.json - added camera lock (1796)

- src/lib/compiler/generateGBVMData.ts
- test/compiler/generateGBVMData.test.ts
Fix
Extra collision flag ASM generation was failing in some cases with empty or invalid flag key values.
Fixes those by ignoring empty values and added some tests. 
No
> [Fix] Update ASM actor extra flags generation

- src/lang/pl.json
Added one line for ROM usage. Update translation so it will have the same lines as en.json
Update of the pl.json
Missing one missing line about toggle ROM usage
Added missing line.
No
Merge ASAP as always. Thank you.
> Update pl.json 2057 - toggle rom usage

- src/lang/pl.json
Update for the pl.json file,
added missing line for the CANVAS_ORIGIN point.
Update for the pl.json
Missing line for the CANVAS_ORIGIN point
Added missing line
No.
As always, merge ASAP, thank you and keep up the good work!
> Update pl.json 2060 - add anchor point
